### ISSUE TITLE
macos Mojave version 10.14.6 running errored

### ISSUE THREAD

**Issue by yiwangwuqian** [singularity/singularity#197] opened 2019-11-18 07:03 UTC
In terminal:python /Users/XXX/Documents/PortGame/singularity/singularity.py

I get log:

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/XXX/Documents/PortGame/singularity/singularity.py", line 26, in <module>
    singularity.main()
  File "/Users/XXX/Documents/PortGame/singularity/singularity/__init__.py", line 312, in main
    data.reload_all()
  File "/Users/XXX/Documents/PortGame/singularity/singularity/code/data.py", line 676, in reload_all
    load_strings()
  File "/Users/XXX/Documents/PortGame/singularity/singularity/code/data.py", line 626, in load_strings
    load_buttons_defs()
  File "/Users/XXX/Documents/PortGame/singularity/singularity/code/data.py", line 600, in load_buttons_defs
    "yes"      : g.hotkey(_("&YES")),
NameError: global name '_' is not defined
```

**Comment by nthykier** [comment] 2019-12-15 16:43
I cannot reproduce this (on Linux) and I don't have a MacOS machine to use for reproducing this bug.  Tagging help wanted accordingly.

What *should* happen is that `singularity.code.i18n` is loaded (it is in the top of `singularity.code.data`) and that ought to inject `_` into `builtins.__dict__` (or `__builtins__.__dict__` if you use python2.7).

@yiwangwuqian: Which version of Python do you use?

**Comment by yiwangwuqian** [comment] 2019-12-17 08:39
> I cannot reproduce this (on Linux) and I don't have a MacOS machine to use for reproducing this bug. Tagging help wanted accordingly.
> 
> What _should_ happen is that `singularity.code.i18n` is loaded (it is in the top of `singularity.code.data`) and that ought to inject `_` into `builtins.__dict__` (or `__builtins__.__dict__` if you use python2.7).
> 
> @yiwangwuqian: Which version of Python do you use?

@nthykier Python 2.7.15

**Comment by Diegus83** [comment] 2020-02-03 17:24
The game works fine in macOS 13 (Catalina) using brew to install Python 3.7 and pip3 to install numpy and pygame. For a guide on getting brew installed see [https://brew.sh/](url)

`brew install python`
`pip 3 install pygame numpy`

I also tried in macOS 14 (Mojave) and the game launches but the window is blank. I can hear the sound effect of the buttons so I know they are there, I just can't see them. If anyone has any idea on how to work around that it would be great.

**Comment by nthykier** [comment] 2020-02-15 13:42
@Diegus83 Thanks for testing and finding a solution. :)

**Comment by nthykier** [comment] 2020-02-16 12:44
Hi @yiwangwuqian,

Can you check if singularity works for you on MacOS Mojave, if you use python 3.7+ with pygame 2.0.0.dev3 or later (note it is a beta release of pygame)?

**Comment by nthykier** [comment] 2020-03-08 20:31
Hi @yiwangwuqian (and other MacOS users that might experience this issue)

We have not heard from you since @Diegus83 found a possible solution that we had hoped you would confirm worked for you.  Therefore, I will now take the liberty of closing the bug in the assumption that it solved your issue.

Should you still experience the issue (with the versions of python and pygame suggested), please let us know and we will reopen the bug.  Should you experience new (different) issues with the proposed versions, please file a new bug for that and we will try to diagnose it from there.

**Closed by nthykier** 2020-03-08 20:31 UTC
Labels: bug, help wanted, need confirmation
