### ISSUE TITLE
Financial Numbers

### ISSUE THREAD

**Issue by PeterJust** [singularity/singularity#74] opened 2018-06-18 21:01 UTC
I have noticed some weird thing in the displayed financial numbers. Sometimes, in the finance tab,  there seems to be no correlation between the money drained and the values displayed. Demarking the units would help. It's unclear, what those numbers represent. Apparently the remaining total income and outgo of the day is displayed. It's necessary to display the current flow as money/unit time and also include such a number in the item description. Therefore it's possible (as a player) to balance income and outgo. The total sum of money flow till midnight might be useful information too, but at the moment, the finance tab is pretty useless shortly before midnight. And it's also quite hard to figure out, what costs will have to be covered the next day.
Also, the money drain while building CPU in a small warehouse seems to be non-linear. In the beginning it's slow and vastly increases some time in the early morning hours. After that it stays steady.

The meaning of the "Cash" and "CPU" numbers in the top right corner is also unclear.

**Comment by Xenega** [comment] 2018-06-19 19:22
If you want to see the current flow of money, you can select 24 hours to see variation in one day (in master version).

The non-linear maintenance drain seems to be a bug. Needs to investigate.

CASH and CPU are 'virtual' units in order to abstract the real 'physical' quantity. CASH could be equivalent to one dollar and CPU could be equivalent to power of one CPU for one day in 2000 (magnitude as one GFlops). I will add help about these units.

**Comment by PeterJust** [comment] 2018-06-19 21:12
Ok thanks!

With "unclear" i meant:
- First number is total cash you own
- second number is debt you owe (?)
- third number is total number of cpu equivalents currently owned
- fourth number is size of cpu pool (?)

**Comment by PeterJust** [comment] 2018-06-21 22:17
I found some evidence (check the attached pictures). Financial numbers are displayed wrong, if the "jobs" slider is unused. Maybe a multiplication with zero somewhere. The 24h display is very neat by the way. It didn't exist in the singularity version 0.30c-1 I got from the repos.

[Financial Report intel.zip](https://github.com/singularity/singularity/files/2125530/Financial.Report.intel.zip)

**Comment by Xenega** [comment] 2018-06-22 14:52
@PeterJust If the jobs slider is unused, jobs are displayed in Pool overflow (Jobs).

**Comment by Xenega** [comment] 2018-06-26 03:06
@PeterJust I fixed some problems with financial numbers (construction cpu and maintenance cpu wrong).
Can you check it?

**Comment by PeterJust** [comment] 2018-06-26 22:31
Still boken. I checked the interactions between the job slider, one research slider (producing load), construction costs (producing load), and the cash in the bank.
Insights:
- the research numbers are only affected, if you've got zero cash in the bank. Compare test series 3 and 6.
- the numbers are directly proportional to the jobs slider. See pictures of test series 6. It seems to calculate the amount of money generated by the jobs slider (CPUamount x JobType). From this it subtracts Maintenance, the rest is allocated to Research. If Research is full, the remainder is allocated to Construction. None of this affects "+ Jobs" and "= Money in 24 h".

Some extra weirdness:
- the numbers are updated, while the game is paused, but jump to something different when resuming time progression. See test series 2.
- The number in braces next to the cash balance. Could you please explain test series 7?

What I also don't really get is the difference between test series 3 and 4. In 4 the construction cost doesn't change, while it does in 3. Maybe it's the amount of cash in the bank (in 4 there is enough to pay for the construction). Maybe the cash is used for maintenance, research and construction until there isn't enough (hence the first picture of 3). Then it starts to consider the inflow by the jobs slider, neglecting the overflown CPU.

Sadly I don't really understand the code. I were unable to figure out all the influences, as my python is a little rusty... But then again, some of the connections are utterly confusing (cash_info in report.py is the result of the method g.pl.give_time in g.py, which is actually defined in player.py which in turn imports the base value for calculation (time_of_day = g.pl.raw_sec) from g.py)

[Financial Report intel 2.zip](https://github.com/singularity/singularity/files/2139183/Financial.Report.intel.2.zip)

**Comment by Xenega** [comment] 2018-06-27 21:03
There a lot problem. :'(

Let's take them one by one.

> the numbers are updated, while the game is paused, but jump to something different when resuming time progression. See test series 2.

It's a feature (lol). In fact, you're allowed to complete 5% more Cash than CPU. Since you have more cash than CPU, the first tick will spend the money difference. 

This is a shitty feature IMHO. It's used certainly to avoid a research blocked with round errors, because cash do not use partial. But we should use a better alternative.

**Comment by Xenega** [comment] 2018-06-27 21:39
After reflection, I don't think we need a alternative. This will work fine without. We will see.

**Comment by PeterJust** [comment] 2018-06-29 06:45
Ok, this is a bit hard to understand, due to grammar. Do I get this right: Any time you spend cash and CPU simultaneously it doesn't have to be spent exactly proportional. Instead, you can spend up to 5% more cash (Example: Warehouse is built 30% of total CPU costs, but 35% of total cash costs).
So when the first tick happens it takes an unusually large chunk of cash from the account, which makes the cashflow in the report pane jump.

What do you mean by "cash do not use partial"?

**Comment by Xenega** [comment] 2018-06-29 09:11
Yes, you're right. I removed this feature/bug.

Cash does not use partial cash unit i.e. decimal cash (example: 0.001). So when you spent cash, you spend a whole cash unit or none.

Sorry for my english.

**Comment by Xenega** [comment] 2018-07-02 19:22
For 7. The number between parenthesis is your future cash: the current cash total less everything that cost you something.

**Comment by PeterJust** [comment] 2018-07-06 20:06
Yeah, don't worry about the english. If something is unclear I'll ask.

Right, so if the cash flow is very small, the process might freeze, because no "whole cash unit" can be spent? Or is it simply not taking away any money then, because of the rounding error? Both options seem to be undesirable. Maybe the first research/jobs simply demand the float. Why not use it? Alternatives: save the first two decimal places as a separate integer. Or just multiply all values internally by 10000 (that seems to be the choice solution for the detection rate and other percentages).

For 7: So this is the total amount of cash you will spent with your current actions? In that case the positive numbers sometimes displayed are somewhat confusing. But I would suggest to replace it with the current total money flow anyway (+- cash per second, minute or hour). The battle over the economy is the main action in the game (you try to build more and better cash/CPU sources, and the game keeps on destroying them). It would instantly display the health of your economy. So this seems to be the much more important number. Other strategy games use this reference as well (for instance [Supreme Commander](http://draginol.stardock.net/images2015/Revisiting-Supreme-Commander_7F36/image_4.png) ->largest numbers in top left box in the image). It would allow to easily set your research sliders exactly so that it consumes just as much as you can produce. 
The total cash and CPU needed for completion of all projects would be good numbers for the financial report IMHO.

**Comment by nthykier** [comment] 2019-08-05 13:17
Hi @PeterJust,

I have written a branch that shows the cash flow in #167 (note the caveats around interest rates and Arbitrage income).  If you have time, it would be great if you could take it for a spin and see if works as intended.

**Comment by nthykier** [comment] 2019-08-07 18:08
For reference, #167 has been merged now.  It still has a caveat around interest rates (it is calculated at the start of the period assuming no other changes rather than smearing it out over the entire time point).

**Comment by PeterJust** [comment] 2019-08-12 22:08
Ok, thanks for the effort! I had a quick look at it (master branch, right?), and i think the number in brackets is still the same. In this picture, i have 10 servers yielding 100 cpu, all doing menial jobs:
![testrecon](https://user-images.githubusercontent.com/32579272/62900904-ac2fd400-bd5b-11e9-8d00-aeb098bee14f.png)
The cash number in brackets should show (100cpu * 5$ / 24h) - (60$  / 24h) = +18,33$/h  (-> aka.: the momentary flowrate), right? But it just shows a number equal to the current cash.

(I noticed the button for "show numbers for next 24h" in the financial pane is gone, which was very useful, imo).

I suggest adding units to the numbers, to clarify their meaning (eg. $, $/h, cpu/h, $/cpu, etc.).

**Comment by nthykier** [comment] 2019-08-13 05:36
PeterJust:
> Ok, thanks for the effort! I had a quick look at it (master branch, right?), and i think the number in brackets is still the same. In this picture, i have 10 servers yielding 100 cpu, all doing menial jobs:
> ![testrecon](https://user-images.githubusercontent.com/32579272/62900904-ac2fd400-bd5b-11e9-8d00-aeb098bee14f.png)
> The cash number in brackets should show (100cpu * 5$ / 24h) - (60$  / 24h) = +18,33$/h  (-> aka.: the momentary flowrate), right? But it just shows a number equal to the current cash.
> 
> (I noticed the button for "show numbers for next 24h" in the financial pane is gone, which was very useful, imo).
> 
> I suggest adding units to the numbers, to clarify their meaning (eg. $, $/h, cpu/h, $/cpu, etc.).
> 
> 

Hi Peter,

Thanks for having a look.

The screenshot looking nothing like the current master branch.  Can you
please double check that you are not using an old version (e.g. 0.30c or
forgot to run "git pull")?  Notably both the 24h report (as you mention
yourself) and the Log screen are missing while both are available on the
master branch.

Attached (hoping here that github deals gracefully with attached images)
is what I see on the master branch with 10 Server Access bases producing
menial jobs while building 6 Server Access bases.  It shows: `CASH: 0
(-145)`

Derived from: `101cpu * 5$ - 600$ (construction) - 50$ (maintenance)`
(it works on days, not hours)

Noting the following bugs:
 * It did not realise that I destroyed my university computer, so it
   should have been 100cpu instead of 101

 * Ditto on the 24 finance screen.

 * The finance screen puts construction at 0 when it really is not.


Adding a "X/DAY" would be a good idea. I will have a look at that. :)

**Comment by PeterJust** [comment] 2019-08-21 21:27
Right, I somehow got the wrong branch, sorry. I checked it again, and it looks improved. But there seem to be some issues left. The sum total is always the same as the earnings. The current money seems to be the sum of the costs (therefore the sum total is always the same as the earnings).
![financial report](https://user-images.githubusercontent.com/32579272/63468242-a7f46c80-c467-11e9-9d8f-6aecb89d4b44.png)

![financial report 2](https://user-images.githubusercontent.com/32579272/63468256-b2166b00-c467-11e9-8e55-dae817df7861.png)
In this picture I'm building a data center and it's 72% finished. Initial cost were 1800 over a buildtime of 24h. Do you think these numbers are correct? There is now cost displayed for building the datacenter. The "jobs" slider is at 0 here. The displayed costs of construction change proportionally to it! There seems to be some ill coupling between the construction cost and the job slider, as well as the current money and the costs.

Also during the construction, the current money is constantly decreasing, while the inflow is constantly increasing (can not be seen in this still picture). 

The income and sum total seem to be calculated correctly.

**Comment by nthykier** [comment] 2019-08-22 06:05
Thanks for retesting.  I have not updated the Financial report at all, so I am not surprised that is still wrong.  However, I am surprised at how wrong it is.

**Comment by nthykier** [comment] 2019-08-22 06:56
@PeterJust Can you include the savegame that reproduces this scenario in the new .s2 format (just for next time)?  This will make easier for me to replicate exactly what you see.

**Comment by PeterJust** [comment] 2019-08-22 19:38
I'm impressed..

Looks good, except that construction cost is still coupled to the jobs slider.

Here is another thing. When building something, it shows an updated flow rate. That's cool! But there seems to be a bug in the calculation. If you select the "buildings" one after another, the flow rate changes inconsistently.  Also sometimes the flowrate value changes after a couple of seconds if you let the selected item sit. Only if you click on an item twice, it shows a consistent flowrate. The flow rate it shows is not consistent between openings of the building window, and is not necessarily the one, the selected building operation would create. Stolen computer time is almost correct, except, that it doesn't consider the processor power needed for building (and therefore estimates the income too high).
[2019-08-22_Testreport_financial_numbers.s2.zip](https://github.com/singularity/singularity/files/3531649/2019-08-22_Testreport_financial_numbers.s2.zip)

**Comment by nthykier** [comment] 2019-08-23 08:00
Thanks for finding the issue with the incorrectly updated resource flow.  I created a separate issue for that (#189).

**Comment by nthykier** [comment] 2019-08-23 08:12
Ok.  I have tried to reproduce the issue about construction costs and the job slider.  I can confirm it on master but not on the `testing/issue-74` branch.  I did spot another bug in there (the time for the "Midnight" report was wrong which made all the numbers wrong).

Can you confirm that it works as intended for you at commit 7a69d7c36e956c353b0ec3d221705d96abe99076?  (The considered buyables are not fixed yet, so that will still be an issue).

**Comment by PeterJust** [comment] 2019-08-27 09:14
Yes, i can confirm, that the job slider coupling seems to be fixed at
commit 7a69d7c

**Comment by nthykier** [comment] 2019-12-15 18:32
Thanks for retesting.  I have opened #204 to track the issue with the flow rates.  As far as I can tell, that is the last bit of this issue, so I will close this issue now.  If you feel I have overlooked another problem in this issue, please open a new issue highlighting it (it is easier to track problems when there is one issue for each of them).

**Closed by nthykier** 2019-12-15 18:32 UTC
Labels: bug, enhancement, question
