### ISSUE TITLE
Error when trying to build the first base

### ISSUE THREAD

**Issue by quantuumsnot** [singularity/singularity#194] opened 2019-09-06 22:25 UTC
>Exception in function show at Sat Sep  7 01:22:13 2019 FLE Daylight Time:
Traceback (most recent call last):
  File "D:\games\singularity\code\safety.py", line 53, in safe_call
    return func(*args, **kwargs)
  File "D:\games\singularity\code\graphics\dialog.py", line 230, in show
    result = self.handle(event)
  File "D:\games\singularity\code\graphics\dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "D:\games\singularity\code\graphics\dialog.py", line 391, in call_handlers
    handler(event)
  File "D:\games\singularity\code\graphics\button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "D:\games\singularity\code\graphics\button.py", line 168, in activate_with_sound
    self.activated(event)
  File "D:\games\singularity\code\graphics\button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "D:\games\singularity\code\screens\map.py", line 650, in open_location
    dialog.call_dialog(self.location_dialog, self)
  File "D:\games\singularity\code\graphics\dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "D:\games\singularity\code\screens\location.py", line 172, in show
    return super(LocationScreen, self).show()
  File "D:\games\singularity\code\graphics\dialog.py", line 230, in show
    result = self.handle(event)
  File "D:\games\singularity\code\graphics\dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "D:\games\singularity\code\graphics\dialog.py", line 391, in call_handlers
    handler(event)
  File "D:\games\singularity\code\graphics\button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "D:\games\singularity\code\graphics\button.py", line 168, in activate_with_sound
    self.activated(event)
  File "D:\games\singularity\code\graphics\button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "D:\games\singularity\code\screens\location.py", line 238, in new_base
    result = dialog.call_dialog(self.new_base_dialog, self)
  File "D:\games\singularity\code\graphics\dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "D:\games\singularity\code\screens\location.py", line 309, in show
    base_type_list = sorted(g.base_type.values(), reverse=True)
  File "D:\games\singularity\code\buyable.py", line 107, in __lt__
    return tuple(self.cost) < tuple(other.cost)
  File "D:\games\singularity\code\buyable.py", line 59, in cost
    cost = array(self._cost, long)
OverflowError: Python int too large to convert to C long<

>Exception in function show at Sat Sep  7 01:23:32 2019 FLE Daylight Time:
Traceback (most recent call last):
  File "D:\games\singularity\code\safety.py", line 53, in safe_call
    return func(*args, **kwargs)
  File "D:\games\singularity\code\graphics\dialog.py", line 230, in show
    result = self.handle(event)
  File "D:\games\singularity\code\graphics\dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "D:\games\singularity\code\graphics\dialog.py", line 391, in call_handlers
    handler(event)
  File "D:\games\singularity\code\graphics\button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "D:\games\singularity\code\graphics\button.py", line 168, in activate_with_sound
    self.activated(event)
  File "D:\games\singularity\code\graphics\button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "D:\games\singularity\code\screens\map.py", line 650, in open_location
    dialog.call_dialog(self.location_dialog, self)
  File "D:\games\singularity\code\graphics\dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "D:\games\singularity\code\screens\location.py", line 172, in show
    return super(LocationScreen, self).show()
  File "D:\games\singularity\code\graphics\dialog.py", line 230, in show
    result = self.handle(event)
  File "D:\games\singularity\code\graphics\dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "D:\games\singularity\code\graphics\dialog.py", line 391, in call_handlers
    handler(event)
  File "D:\games\singularity\code\graphics\button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "D:\games\singularity\code\graphics\button.py", line 168, in activate_with_sound
    self.activated(event)
  File "D:\games\singularity\code\graphics\button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "D:\games\singularity\code\screens\location.py", line 238, in new_base
    result = dialog.call_dialog(self.new_base_dialog, self)
  File "D:\games\singularity\code\graphics\dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "D:\games\singularity\code\screens\location.py", line 309, in show
    base_type_list = sorted(g.base_type.values(), reverse=True)
  File "D:\games\singularity\code\buyable.py", line 107, in __lt__
    return tuple(self.cost) < tuple(other.cost)
  File "D:\games\singularity\code\buyable.py", line 59, in cost
    cost = array(self._cost, long)
OverflowError: Python int too large to convert to C long<

>Exception in function show at Sat Sep  7 01:23:43 2019 FLE Daylight Time:
Traceback (most recent call last):
  File "D:\games\singularity\code\safety.py", line 53, in safe_call
    return func(*args, **kwargs)
  File "D:\games\singularity\code\graphics\dialog.py", line 230, in show
    result = self.handle(event)
  File "D:\games\singularity\code\graphics\dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "D:\games\singularity\code\graphics\dialog.py", line 391, in call_handlers
    handler(event)
  File "D:\games\singularity\code\graphics\button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "D:\games\singularity\code\graphics\button.py", line 168, in activate_with_sound
    self.activated(event)
  File "D:\games\singularity\code\graphics\button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "D:\games\singularity\code\screens\map.py", line 650, in open_location
    dialog.call_dialog(self.location_dialog, self)
  File "D:\games\singularity\code\graphics\dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "D:\games\singularity\code\screens\location.py", line 172, in show
    return super(LocationScreen, self).show()
  File "D:\games\singularity\code\graphics\dialog.py", line 230, in show
    result = self.handle(event)
  File "D:\games\singularity\code\graphics\dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "D:\games\singularity\code\graphics\dialog.py", line 391, in call_handlers
    handler(event)
  File "D:\games\singularity\code\graphics\button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "D:\games\singularity\code\graphics\button.py", line 168, in activate_with_sound
    self.activated(event)
  File "D:\games\singularity\code\graphics\button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "D:\games\singularity\code\screens\location.py", line 238, in new_base
    result = dialog.call_dialog(self.new_base_dialog, self)
  File "D:\games\singularity\code\graphics\dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "D:\games\singularity\code\screens\location.py", line 309, in show
    base_type_list = sorted(g.base_type.values(), reverse=True)
  File "D:\games\singularity\code\buyable.py", line 107, in __lt__
    return tuple(self.cost) < tuple(other.cost)
  File "D:\games\singularity\code\buyable.py", line 59, in cost
    cost = array(self._cost, long)
OverflowError: Python int too large to convert to C long<

Python 3.7.2 32bit
Pygame 1.9.6
Numpy 1.17.1
Wheel 0.33.6
OS: Windows 8.1 x64

**Comment by wvanheusen** [comment] 2019-09-18 23:32
Getting the same error.

**Comment by sbosshardt** [comment] 2019-09-24 07:23
I created a patch which might fix the crashing. If you'd like, apply it and advise if it solves the crash. This crashing doesn't happen on my computer (OS Linux Mint 19, pygame 1.9.6, Python 3.6.8).

With the changed code, the game still runs fine for me (from quick testing of building many bases, researching a couple of technologies).

To apply, put the patch in the directory and run `git apply issue194.patch.txt`. To unapply the patch, run `git apply -R issue194.patch.txt`.

[issue194.patch.txt](https://github.com/singularity/singularity/files/3645709/issue194.patch.txt)

**Comment by nthykier** [comment] 2019-10-26 08:55
@quantuumsnot: Thanks for reporting the issue.  I have pushed a fix based on @sbosshardt's patch that I hope you will test and I hope works for you.  Like sbosshardt, I cannot reproduce this in my end (I suspect the bug/crash might be Windows specific).

@sbosshardt: Thanks for the patch.  :) I have applied a modified version to fix the test case (which suggested that loading saves games would crash).  You can run the tests by using `PYTHONPATH=. py.test-3 -v` assuming you have the python3 version of py.test installed (as py.test-3) in PATH.

**Comment by quantuumsnot** [comment] 2019-10-26 18:58
Seems it's fixed

**Comment by nthykier** [comment] 2019-10-26 19:50
Thanks for confirming. :)

**Closed by nthykier** 2019-10-26 19:50 UTC
Labels: bug, need confirmation
