### ISSUE TITLE
Better keyboard support for creating CPUs in a base

### ISSUE THREAD

**Issue by danuker** [singularity/singularity#209] opened 2019-12-20 15:48 UTC
When playing using the keyboard, stuff is moving so fast on my screen, that I really feel like a computer/AI! After building a base, I can go to the continent, select the new empty base, type `O R <enter> N <enter> S <enter>` and I get the best reactor, network, and security available. This is very fast and enjoyable!

But I found a point of friction when building the CPUs. It is quite hard to tab over the CPU count, and increase the amount. Typing into the number box does not replace the number, and deleting it replaces the text with a "1". And I can't seem to be able to focus the scrollbar using Tab (at least I'm not able to see it).

I think an improvement here would be a "+" button, and when the user presses "+" (or "=", the "lowercase" of "+", heh) on the keyboard, it increases the amount of CPUs to build (scroll the scrollbar). Also, a "-" might be useful when the user notices they are overspending, and wants to go back also with the keyboard.

**Edit**: I think the scrollbar should move say, 10%, of the total width, and not just a single CPU. It would be hard to press it 200 times (when filling up a moon base).

Here is a mock-up:
![plus-minus](https://user-images.githubusercontent.com/74835/71266375-ea17b700-2350-11ea-9ee7-8a7e9f0fd514.png)

**Comment by nthykier** [comment] 2019-12-21 09:00
Conceptually, there is no reason why we could not have "UP + DOWN" go to the listbox, "LEFT + RIGHT" to the slider, "numeric + BACKSPACE + DELETE" go to the text field.  The problem is to make it work smoothly and in other cases as well (e.g. the `ResearchScreen`).

I have made a conceptual draft in the branch `wip-better-hot-keys-in-base-dialog` for what it takes.  Though:

 * The slider hotkeys are not working yet (it did in the previous commit of the branch but I do not understand how it regressed)
 * I am not sure the implementation is the "right approach".
 * The text field is weird to say the least - backspace is not working at all how I would expect it to.

Anyway, feel free to take it for a spin and propose improvements.

**Comment by rofl0r** [comment] 2019-12-21 15:06
probably related: https://github.com/singularity/singularity/issues/16

**Comment by danuker** [comment] 2019-12-22 02:14
@nthykier I tried to debug what is going on, and it seems the new `_got_key` from `screens/base.py` is only called during pygame.KEYUP events, but not KEYDOWN also.

The most important difference from the previous commit (that is working) is that you now use `add_handler` instead of `add_key_handler`. This means you now use `Dialog`'s `handlers` dict instead of `key_handlers`.

I suspect this leads to the `handle` method of `Dialog` to handle it differently; I think what you're interested in is `singularity/singularity/code/dialog.py` lines 304 to 354.

I suspect the way `handle` uses KEYUP and KEYDOWN is for repetition of a handler when holding a button - so it has to know which buttons are pressed (so perhaps you can't or shouldn't add a "universal" handler for the keys, but a key-ish one). But this is speculation, I haven't understood the code.

This is as far as I got debugging; I will go to sleep now (4AM here :) Hope this helps anyway. I tried out the commit before and I would be happy with left/right instead of +/- also. I thank you very much for your work and appreciate it!

**Comment by nthykier** [comment] 2019-12-22 08:18
Dan Haiduc:
> @nthykier I tried to debug what is going on, and it seems the new `_got_key` from `screens/base.py` is only called during pygame.KEYUP events, but not KEYDOWN also.
> 
> The most important difference from the previous commit (that is working) is that you now use `add_handler` instead of `add_key_handler`. This means you now use `Dialog`'s `handlers` dict instead of `key_handlers`.
> 
> I suspect this leads to the `handle` method of `Dialog` to handle it differently; I think what you're interested in is `singularity/singularity/code/dialog.py` lines 304 to 354.
> 

Thanks for following up on it and helping me spot the issue. :)  The
underlying issue was that I should have used `constants.KEY` instead of
`pygame.KEYDOWN`.

> [...]
> 
> This is as far as I got debugging; I will go to sleep now (4AM here :) Hope this helps anyway. I tried out the commit before and I would be happy with left/right instead of +/- also. I thank you very much for your work and appreciate it!
> 

It helped very much. :)

 * The slider now works! \o/
 * Typing numbers in the text field is now less "surprising".


Please take it for a spin again and see if it works as intended.

**Comment by nthykier** [comment] 2019-12-22 08:50
> probably related: #16

@rofl0r Personally, I think #146 is more likely and suitable for the game with #16 being closed as `wontfix` eventually as it does not match the current game mechanics.  The alternative here is changing the game mechanics where many bases is not an issue for the player (or positive).

**Comment by danuker** [comment] 2019-12-22 10:52
@nthykier Thanks for the fix! The slider and the number input works nicely now!

But while attempting to play using only the keyboard, I found an issue someplace else, which I did not notice before: after starting the game, you can't move up/down in any list before clicking each with a mouse (they don't seem focused). But I will open a new ticket for it, because this one is fixed as soon as you merge (and/or squash) the branch!

**Comment by nthykier** [comment] 2019-12-23 07:36
Thanks for testing and confirming it works. :)

I noticed the list issue (that you reported as #211) as well.  This is partly why I was concerned about whether this was the right approach - I will have to sprinkle it all over the codebase to fix it.

**Closed** 2019-12-23 08:23 UTC

**Comment by danuker** [comment] 2019-12-23 12:24
Thank you for the awesome work!

**Comment by nthykier** [comment] 2019-12-23 17:06
Dan Haiduc:
> Thank you for the awesome work!
> 

You are welcome. :)  Thanks for testing and providing suggestions for
improvements. :)
